spring.application.name=calendar

spring.datasource.url=jdbc:postgresql://localhost:5432/calendar_local_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

security.cors.allowedOrigins=${allowedOrigins:*}

# logging.file.name=log.txt
logging.structured.format.file=ecs

#Spring Boot Actuator
info.app.name=GarboApp Calendar Service
info.app.description=Self explanatory
info.app.version=0.0.1-SNAPSHOT
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
