spring.application.name=calendar

spring.datasource.url=jdbc:postgresql://localhost:5432/local_db
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.open-in-view=false

security.cors.allowedOrigins=${allowedOrigins:*}
security.basic.enabled=false

logging.structured.format.file=ecs
# logging.file.name=log.txt
